
# test files

sudo: false

install:
- npm install -g recess stylus
- npm install

addons:
  apt:
    packages:
    - docutils

script:
- grunt
- rst2html ReadMe.rst build/html/ReadMe.html

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

