
# Id: jenkins-userContent/0.0.2-master 

# Configuration for containerized test build at travis-ci.org or compatible stacks.

addons:
  apt:
    packages:
    - uuid-runtime

sudo: false

install:
- echo PATH=$PATH
- export PATH=$PATH:$HOME/.local/bin
- echo PATH=$PATH

# XXX: test
#- mkdir -vp $HOME/build $HOME/.local/{bin,lib}

- test -n "$(which stylus)" || npm install -g stylus
- test -n "$(which recess)" || npm install -g recess
- test -n "$(which grunt)" || npm install -g grunt grunt-cli
- test -n "$(which bower)" || npm install -g bower

- npm install

- pip install --user docutils

- git clean -df

script:
#- grunt --env=$ENV
#- echo PATH=$PATH
#- export PATH=$PATH:$HOME/.local/bin
#- echo PATH=$PATH
- ./script/sh/ci.sh

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

