
# Id: jenkins-userContent/0.0.2-master 

# Configuration for containerized test build at travis-ci.org or compatible stacks.

sudo: false

install:
- test -n "$(which stylus)" || npm install -g stylus
- test -n "$(which recess)" || npm install -g recess
- test -n "$(which grunt)" || npm install -g grunt grunt-cli
- rm -rf $HOME/build
- mkdir -vp $HOME/build $HOME/.local/{bin,lib}
- git clone https://github.com/dotmpe/git-versioning.git $HOME/build/git-versioning
- echo PATH=$PATH
- export PATH=$PATH:$HOME/.local/bin
- echo PATH=$PATH
- test -n "$(which git-versioning)" || ( cd $HOME/build/git-versioning && ./configure.sh $HOME/.local && ENV=production ./install.sh )
- npm install
- pip install --user docutils

script:
#- grunt shell:generateFeatures -env=$ENV --features="bootstrap-css doony-css extra-css doony-js extra-js"
#- grunt --env=$ENV
- echo PATH=$PATH
- export PATH=$PATH:$HOME/.local/bin
- echo PATH=$PATH
- git clean -df
- pwd
- pwd -P
- ls -la 
- grunt
- test -w "$HOME/userContent" && { cp -v userContent.{css,js} $HOME/userContent/; } || echo "Note userContent is not writable, no files installed"
- mkdir -vp build/html
- rst2html.py ReadMe.rst build/html/ReadMe.html

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

