
# Id: jenkins-userContent/0.0.2-master 

# Configuration for containerized test build at travis-ci.org or compatible stacks.

sudo: false

install:
- echo PATH=$PATH
- export PATH=$PATH:$HOME/.local/bin
- echo PATH=$PATH

# XXX: test
#- mkdir -vp $HOME/build $HOME/.local/{bin,lib}

- npm install

- pip install --user docutils

- git clean -df

script:
#- grunt --env=$ENV
- echo PATH=$PATH
- bats --version
- git-versioning 
- uuidgen
- ./script/sh/ci.sh
- grep '^nok' build.tap && { echo "Errors in build"; exit 1; } || { echo "No errors in build"; }

branches:
  only:
  - '/.*test$/'
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

