
# test files

sudo: false

install:
- test -x $(which stylus) || npm install -g stylus
- test -x $(which recess) || npm install -g recess
- test -x $(which grunt) || npm install -g grunt grunt-cli
- npm install
- pip install --user docutils

script:
- grunt
- mkdir -vp build/html
- rst2html.py ReadMe.rst build/html/ReadMe.html

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

