
# Id: jenkins-userContent/0.0.2-master 

# Configuration for containerized test build at travis-ci.org or compatible stacks.

sudo: false

install:
- test -n "$(which stylus)" || npm install -g stylus
- test -n "$(which recess)" || npm install -g recess
- test -n "$(which grunt)" || npm install -g grunt grunt-cli
- npm install
- pip install --user docutils

script:
#- grunt shell:generateFeatures -env=$ENV --features="bootstrap-css doony-css extra-css doony-js extra-js"
#- grunt --env=$ENV
- git clean -df
- pwd
- pwd -P
- ls -la 
- grunt
- test -w "$HOME/userContent" && { cp -v userContent.{css,js} $HOME/userContent/; } || echo "Note userContent is not writable, no files installed"
- mkdir -vp build/html
- rst2html.py ReadMe.rst build/html/ReadMe.html

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

