#/bin/sh

set -e

. ./script/sh/util.sh

# Id: jenkins-userContent/0.0.3 build-userContent-js.sh


id="jenkins-ci.jenkins-usercontent/0.0.3"
out=userContent.js
date=`date`

test -n "$1" || exit 12
build_features="$(echo $(get_properties < $1))"


echo "/* This file is auto-generated by $id: $0 on $date  */" > $out

case " $build_features " in *" doony-js "* )
  echo "/* jshint ignore:start */" >> $out
  cat node_modules/doony/doony.js >> $out
  echo "/* jshint ignore:end */" >> $out
;; esac

case " $build_features " in *" extra-js "* )
  cat extras.js >> $out
;; esac

# Update JSON-editor behaviour
cat jenkins-json-param-editor.js >> $out

echo "/* jshint ignore:start */" >>$out

#cat bower_components/underscore/underscore-min.js >> $out

cat bower_components/jquery-jsonview/dist/jquery.jsonview.js >>$out

#cat bower_components/handlebars/handlebars. >>$out
cat bower_components/handlebars.js/dist/handlebars.js >>$out
echo "/* jshint ignore:end */" >>$out

#cat bower_components/handlebars-helpers/src/helpers.js >>$out

cat hbs-replace.js >>$out

