#/bin/sh

id="jenkins-ci.jenkins-usercontent/0.0.2"
out=userContent.js
date=`date`

echo "/* This file is auto-generated by $id: $0 on $date  */" > $out

#cat node_modules/doony/doony.js >> $out

cat extras.js >> $out

