
# Project package metadata file 
# (github:dotmpe/script-mpe/schema/package.yml)

- id: jenkins-userContent
  main: jenkins-userContent
  version: 0.0.4-dev # jenkins-userContent
  environments: ['dev']

  # Sh scripts
  init:
   - npm install
   # Which equals:
   #- Build_Deps_Default_Paths=1 ./install-dependencies.sh -
   #- npm install
   #- bower install
   #- grunt build
  check:
   - grunt check
  build:
   - grunt build
  test:
   - grunt test

  # Pd per-project config
  pd-meta:
    tasks:
      slug: JNK-UC
    # XXX: JNK-UC-1: Would need some new package schema to generate/update NPM
    npm:
      test:
        - 'pd:check'
        - 'pd:test'
      install:
        - 'pd:check'
        - 'pd:test'

