/* This file is auto-generated by jenkins-ci.jenkins-usercontent/0.0.2: ./build-userContent-js.sh on Sun Aug 30 05:39:44 CEST 2015  */
window.jQuery('table#projectstatus th[width=1]').attr('width', '');
